name: Build and Release

on:
  workflow_dispatch:
    branches:
      - master
    inputs:
      ReleaseType:
        type: choice
        description: 'Type of Release'
        required: true
        options:
          - MAJOR
          - MINOR
          - PATCH
          - BETA

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install semver
        run: npm install -g semver

      - name: Fetch the latest tag
        id: fetch-tag
        run: |
          git fetch --tags
          latestTag=$(git tag -l | sort -V | tail -n 1)
          echo "Latest tag: $latestTag"
          echo "LATEST_TAG=$latestTag" >> $GITHUB_ENV

      - name: Determine new version
        id: determine-version
        run: |
          currentVersion=${{ env.LATEST_TAG }}
          releaseType=${{ github.event.inputs.ReleaseType }}
          
          case $releaseType in
            MAJOR)
              newVersion=$(semver --increment major $currentVersion)
              ;;
            MINOR)
              newVersion=$(semver --increment minor $currentVersion)
              ;;
            PATCH)
              newVersion=$(semver --increment patch $currentVersion)
              ;;
            BETA)
              if [[ $currentVersion =~ -beta\.([0-9]+)$ ]]; then
                betaCount=$((BASH_REMATCH[1]+1))
              else
                betaCount=1
              fi
              newVersion="${currentVersion}-beta.${betaCount}"
              ;;
            *)
              echo "Invalid ReleaseType provided."
              exit 1
              ;;
          esac

          echo "New version: $newVersion"
          echo "NEW_VERSION=$newVersion" >> $GITHUB_ENV

      - name: Create Tag and Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |          
          git tag $NEW_VERSION
          git push origin $NEW_VERSION
          releaseNotes="Release $newVersion"

          # Check if the release already exists
          if ! gh release view $NEW_VERSION >/dev/null 2>&1; then
            gh release create $NEW_VERSION -t "$NEW_VERSION" -n "$releaseNotes"
          fi