name: Build and Release

on:
  workflow_dispatch:
    branches:
      - master
    inputs:
      ReleaseType:
        type: choice
        description: 'Type of Release'
        required: true
        options:
          - MAJOR
          - MINOR
          - PATCH
          - BETA

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - uses: actions/checkout@v3

      # - uses: wemogy/next-release-version-action@1.0.1
      #   id: release-version
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     branch: 'release/v1.1'

      - uses: actions/setup-node@v4 # Example for Node.js, adjust for your environment
        with:
          node-version: 16
      - run: npm install -g git-semver # Install git-semver for history analysis

      - name: Analyze git history
        id: analyze-history
        run: git-semver -i --tag-pattern "v*.*.*" # Analyze history, assuming tags start with "v"

      - name: Extract version information
        id: extract-version
        run: echo "::set-output name=new_version::$(cat ${{ steps.analyze-history.outputs.stdout }} | grep 'next version')"
