name: Build and Release

on:
  workflow_dispatch:
    branches:
      - master
    inputs:
      ReleaseType:
        type: choice
        description: 'Type of Release'
        required: true
        options:
          - MAJOR
          - MINOR
          - PATCH
          - BETA

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - uses: actions/checkout@v3

      # install requirements
      - name: Install requirements
        run: poetry install --only semver
      # semantic release
      - name: Python Semantic Release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          set -o pipefail
          # Set git details
          git config --global user.name "github-actions"
          git config --global user.email "bpuri@pfizer.com"
          # run semantic-release
          poetry run semantic-release publish -v DEBUG -D commit_author="github-actions <bpuri@pfizer.com>"