name: Release

on:
  workflow_dispatch:
    branches:
      - master
    inputs:
      deployment_tag: ${{ inputs.deployment_tag }}

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Generate semantic version
        id: semver
        uses: cycjimmy/semantic-release-action@v3
        with:
          dry-run: true  # Only calculate the version, don't create a release
          git-tags: ${{ inputs.deployment_tag }}  # Use deployment tag for versioning

      - name: Create release
        if: success()
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.semver.outputs.version }}
          release_name: Release ${{ steps.semver.outputs.version }}
          body: |
            **Deployed:** ${{ inputs.deployment_tag }}
            **Changes:**
            - (Analyze git history from ${{ inputs.deployment_tag }} and list changes here)

