name: Build and Release

on:
  workflow_dispatch:
    branches:
      - master
    inputs:
      ReleaseType:
        type: choice
        description: 'Type of Release'
        required: true
        options:
          - MAJOR
          - MINOR
          - PATCH
          - BETA

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install git-semver utility
        run: npm install -g git-semver

      # - name: Fetch the latest tag
      #   id: fetch-latest-tag
      #   run: |
      #     latestTag=$(git tag -l | sort -V | tail -n 1)
      #     echo "Latest tag: $latestTag"
      #     echo "::set-output name=latestTag::$latestTag"

      - name: Fetch the latest tag
        run: |
          git fetch --tags
          latestTag=$(git tag -l | sort -V | tail -n 1)
          echo "Latest tag: $latestTag" >> $GITHUB_ENV

      - name: Set output for later steps
        run: echo "::set-output name=latestTag::$latestTag"


      - name: Determine new version
        id: determine-version
        run: |
          currentVersion=${{ steps.fetch-latest-tag.outputs.latestTag }}
          newVersion=$(git semver --increment ${{ github.event_name }} --from $currentVersion)
          echo "New version: $newVersion"
          echo "::set-output name=newVersion::$newVersion"

      - name: Set version as an environment variable
        run: echo "RELEASE_VERSION=${{ steps.determine-version.outputs.newVersion }}" >> $GITHUB_ENV

      - name: Tag and push
        run: |
          git tag $RELEASE_VERSION
          git push origin $RELEASE_VERSION