name: Use Shared Workflow

on:
  workflow_dispatch:
    inputs:
      ReleaseType:
        type: choice
        description: 'Type of Release'
        required: true
        options:
          - MAJOR
          - MINOR
          - PATCH
          - BETA
      Environment:
        type: choice
        description: 'The environment to deploy to'
        required: true
        options:
          - test
          - prod
      Release:
        description: 'Production release name'
        required: false
        default: 'latest'

jobs:
  semantic-versioning:
    runs-on: ubuntu-latest
    
    steps:
      - name: Use Shared Semantic Versioning Workflow
        uses: purib/nginx-hello-world@main
        with:
          ReleaseType: ${{ github.event.inputs.ReleaseType }}
          Environment: ${{ github.event.inputs.Environment }}
          Release: ${{ github.event.inputs.Release }}
