name: Use Shared Workflow

on:
  workflow_dispatch:
    inputs:
      ReleaseType:
        type: choice
        description: 'Type of Release'
        required: true
        options:
          - MAJOR
          - MINOR
          - PATCH
          - BETA
      Environment:
        type: choice
        description: 'The environment to deploy to'
        required: true
        options:
          - test
          - prod
      Release:
        description: 'Production release name'
        required: false
        default: 'latest'

jobs:
  call-semantic-versioning:
    if: ${{ github.event.inputs.Environment == 'test' }}
    uses: purib/sharedworflows/.github/workflows/semantic.yml@main
    with:
      ReleaseType: ${{ github.event.inputs.ReleaseType }}
