name: Use Shared Workflow

on:
  workflow_dispatch:
    inputs:
      ReleaseType:
        type: choice
        description: 'Type of Release'
        required: true
        options:
          - MAJOR
          - MINOR
          - PATCH
          - BETA
      Environment:
        type: choice
        description: 'The environment to deploy to'
        required: true
        options:
          - test
          - prod
      Release:
        description: 'Production release name'
        required: false
        default: 'latest'

jobs:
  call-semantic-versioning:
    uses: ./.github/workflows/semantic.yml
    with:
      ReleaseType: ${{ github.event.inputs.ReleaseType }}
      Environment: ${{ github.event.inputs.Environment }}